name: Deploy static content to Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Upload website content
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Change this if your HTML files are in a folder like 'public'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2

